language: swift
osx_image: xcode9.3
xcode_project: HM10 Serial.xcodeproj
xcode_scheme: HM10 Serial
before_install:
  - openssl aes-256-cbc -K $encrypted_342f2f6ad141_key -iv $encrypted_342f2f6ad141_iv
    -in ffbc5369-a89d-49dd-90f4-dc27873ed729.mobileprovision.enc -out ffbc5369-a89d-49dd-90f4-dc27873ed729.mobileprovision
    -d
  - mkdir -p "~/Library/MobileDevice/Provisioning\ Profiles/"
  - mv ffbc5369-a89d-49dd-90f4-dc27873ed729.mobileprovision "~/Library/MobileDevice/Provisioning\ Profiles/"
script:
  - set -o pipefail && xcodebuild -project HM10\ Serial.xcodeproj -allowProvisioningUpdates # | xcpretty
